/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Heart_Rate_input.h>
#include <Heart_Rate_input_aliases.h>
#include <SW2_Switch.h>
#include <SW2_Switch_aliases.h>
#include <Button_output.h>
#include <Button_output_aliases.h>
#include <Wakeup_ISR.h>
#include <Led_Advertising_Green.h>
#include <Led_Advertising_Green_aliases.h>
#include <Led_Connected_Blue.h>
#include <Led_Connected_Blue_aliases.h>
#include <ADC.h>
#include <Opamp.h>
#include <BLE_gatt.h>
#include <BLE.h>
#include <BLE_hrs.h>
#include <BLE_HAL_PVT.h>
#include <BLE_STACK_PVT.h>
#include <BLE_StackGap.h>
#include <BLE_StackGatt.h>
#include <BLE_StackGattDb.h>
#include <BLE_StackHostMain.h>
#include <BLE_StackL2cap.h>
#include <BLE_dis.h>
#include <BLE_StackGattServer.h>
#include <BLE_StackGattClient.h>
#include <BLE_Stack.h>
#include <BLE_eventHandler.h>
#include <ADC_IRQ.h>
#include <ADC_intClock.h>
#include <BLE_bless_isr.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

